In [4]:
#Ryan Usher

import numpy as np
import tensorflow as tf

In [5]:
#Question 1.)

#Problem 4.)

x=  tf.range(24)
x = tf.reshape(x, (2,3,4))
len(x)


2

Question 1.)
Problem 5:

Yes, 0

In [6]:
#Question 1.)

#Problem 6.)

A = tf.reshape(tf.range(6, dtype=tf.float32), (2, 3))
A / A.sum(axis=1)


AttributeError: ignored

In [7]:
#Question 2.)

#2A.)

a = np.array([[1], [-2], [3], [2]])
b = np.array([[2], [-3], [1], [-1]])


c = np.dot(a, np.transpose(b))
d = np.dot(np.transpose(a), b)

print("C= ", c)
print("D= ", d)

C=  [[ 2 -3  1 -1]
 [-4  6 -2  2]
 [ 6 -9  3 -3]
 [ 4 -6  2 -2]]
D=  [[9]]


In [8]:
#2b.)

In [9]:
#2c.)

a = tf.range(20)
tf.reshape(a, (5,4))

<tf.Tensor: shape=(5, 4), dtype=int32, numpy=
array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]], dtype=int32)>

In [10]:
#2d.)

c = tf.reshape(a, (5,4)) * tf.reshape(a, (5,4))

print("C= ", c)

C=  tf.Tensor(
[[  0   1   4   9]
 [ 16  25  36  49]
 [ 64  81 100 121]
 [144 169 196 225]
 [256 289 324 361]], shape=(5, 4), dtype=int32)


In [11]:
#Question 3.)

#3a.)

b = tf.range(24)
b = tf.reshape(b, (2,3,4))

In [12]:
#3b.)

tf.reduce_sum(b)

<tf.Tensor: shape=(), dtype=int32, numpy=276>

In [13]:
#3c.)

c = b[0]
d = b[1]
print("C= ", c)
print("D= ", d)

C=  tf.Tensor(
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]], shape=(3, 4), dtype=int32)
D=  tf.Tensor(
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]], shape=(3, 4), dtype=int32)
